apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: awstoronto
spec:
  selector:
    matchLabels:
      app: awstoronto
  replicas: 10 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: awstoronto
    spec:
      containers:
      - name: awstoronto
        image: docker.io/poitocontainer/awstoronto:v2
        ports:
        - containerPort: 80
