apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: awstorontorolling
spec:
  selector:
    matchLabels:
      app: awstoronto
  replicas: 8 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: awstorontorolling
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxsurge: 1
      maxUnavailable: 0
    spec:
      containers:
      - name: awstorontorolling
        image: docker.io/poitocontainer/awstoronto:v3
        ports:
        - containerPort: 80
