apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: gtsnutanixv1
spec:
  selector:
    matchLabels:
      app: gtsnutanixv1
  replicas: 5 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: gtsnutanixv1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    spec:
      containers:
      - name: gtsnutanixv1
        image: docker.io/poitocontainer/awsdrupaldbembedded:v2
        ports:
        - containerPort: 80
